import random

def choose_word(category):
    words = {
        'animals': ['python', 'elephant', 'tiger', 'kangaroo', 'giraffe', 'lion', 'zebra', 'bear', 'panda', 'horse',
                    'deer', 'wolf', 'fox', 'raccoon', 'rabbit', 'squirrel', 'bat', 'seal', 'whale', 'dolphin',
                    'eagle', 'hawk', 'owl', 'parrot', 'penguin', 'shark', 'octopus', 'jellyfish', 'crab', 'lobster',
                    'starfish', 'sea urchin', 'moose', 'buffalo', 'hamster', 'beetle', 'antelope', 'monkey', 'lemur'],
        'fruits': ['apple', 'banana', 'grape', 'mango', 'strawberry', 'blueberry', 'blackberry', 'pear', 'peach', 'plum',
                   'kiwi', 'pineapple', 'cherry', 'pomegranate', 'fig', 'date', 'apricot', 'cantaloupe', 'nectarine', 'grapefruit',
                   'watermelon', 'raspberry', 'lime', 'lemon', 'orange', 'tangerine', 'coconut', 'passionfruit', 'dragonfruit', 'guava',
                   'kiwi', 'starfruit', 'persimmon', 'papaya', 'avocado', 'jackfruit', 'durian', 'lychee', 'mangosteen'],
        'countries': ['canada', 'brazil', 'india', 'germany', 'australia', 'france', 'italy', 'spain', 'china', 'japan',
                      'mexico', 'uk', 'south africa', 'netherlands', 'sweden', 'norway', 'denmark', 'finland', 'switzerland', 'belgium',
                      'austria', 'greece', 'portugal', 'ireland', 'poland', 'czechia', 'hungary', 'romania', 'turkey', 'israel',
                      'saudi arabia', 'united arab emirates', 'qatar', 'singapore', 'south korea', 'new zealand', 'philippines', 'malaysia',
                      'vietnam', 'thailand', 'indonesia', 'colombia', 'argentina', 'chile', 'peru', 'uruguay', 'paraguay', 'bolivia'],
        'vehicles': ['car', 'bicycle', 'motorcycle', 'bus', 'train', 'airplane', 'boat', 'helicopter', 'scooter', 'truck',
                     'van', 'submarine', 'spaceship', 'yacht', 'skateboard', 'tractor', 'ambulance', 'firetruck', 'trolley', 'hovercraft',
                     'rickshaw', 'snowmobile', 'jet ski', 'moped', 'limousine', 'cargo ship', 'ferry', 'speedboat', 'hot air balloon', 'gondola',
                     'zeppelin', 'segway', 'balloon', 'cable car'],
        'sports': ['soccer', 'basketball', 'baseball', 'tennis', 'volleyball', 'hockey', 'golf', 'swimming', 'running', 'cycling',
                   'boxing', 'wrestling', 'skating', 'skiing', 'snowboarding', 'surfing', 'cricket', 'rugby', 'handball', 'badminton',
                   'archery', 'fencing', 'table tennis', 'karate', 'judo', 'taekwondo', 'squash', 'gymnastics', 'dancing', 'equestrian',
                   'canoeing', 'rowing', 'sailing', 'billiards'],
        'foods': ['pizza', 'burger', 'pasta', 'sushi', 'tacos', 'salad', 'soup', 'sandwich', 'steak', 'chicken', 'fish', 'rice',
                  'curry', 'noodles', 'dumplings', 'chocolate', 'ice cream', 'cake', 'cookies', 'bread', 'pancakes', 'waffles', 'omelette',
                  'pasta', 'lasagna', 'burrito', 'samosa', 'spring rolls', 'falafel', 'kebab', 'nachos', 'grilled cheese', 'hot dog'],
        'music': ['guitar', 'piano', 'violin', 'drums', 'trumpet', 'saxophone', 'flute', 'clarinet', 'cello', 'trombone', 'harp',
                  'accordion', 'banjo', 'mandolin', 'sitar', 'ukulele', 'synthesizer', 'drum kit', 'xylophone', 'conga', 'bongo',
                  'harmonica', 'maracas', 'oboe', 'bassoon', 'tuba', 'French horn', 'bagpipes', 'organ', 'keyboard', 'double bass',
                  'theremin', 'zither', 'digeridoo', 'euphonium'],
        'instruments': ['guitar', 'piano', 'violin', 'drums', 'trumpet', 'saxophone', 'flute', 'clarinet', 'cello', 'trombone',
                        'harp', 'accordion', 'banjo', 'mandolin', 'sitar', 'ukulele', 'synthesizer', 'drum kit', 'xylophone', 'conga',
                        'bongo', 'harmonica', 'maracas', 'oboe', 'bassoon', 'tuba', 'French horn', 'bagpipes', 'organ', 'keyboard',
                        'double bass', 'theremin', 'zither', 'digeridoo', 'euphonium'],
        'movies': ['inception', 'avatar', 'titanic', 'gladiator', 'joker', 'pulp fiction', 'fight club', 'memento', 'matrix', 'interstellar',
                   'dunkirk', 'shutter island', 'seven', 'the godfather', 'the dark knight', 'goodfellas', 'forrest gump', 'et', 'jaws',
                   'star wars', 'the lord of the rings', 'back to the future', 'jurassic park', 'the shawshank redemption', 'pulp fiction',
                   'the silence of the lambs', 'the departed', 'fight club', 'se7en', 'casablanca', 'the usual suspects', 'alien'],
        'books': ['harry potter', 'lord of the rings', 'the hobbit', '1984', 'brave new world', 'moby dick', 'to kill a mockingbird', 'gatsby',
                  'the catcher in the rye', 'pride and prejudice', 'the great gatsby', 'wuthering heights', 'the odyssey', 'jane eyre',
                  'animal farm', 'crime and punishment', 'the count of monte cristo', 'little women', 'the chronicles of narnia', 'catch-22',
                  'the road', 'beloved', 'the handmaid’s tale', 'the picture of dorian gray', 'frankenstein', 'dracula', 'the shinning',
                  'the da vinci code', 'life of pi', 'the alchemist', 'the girl with the dragon tattoo', 'the hunger games'],
        'animals': ['python', 'elephant', 'tiger', 'kangaroo', 'giraffe', 'lion', 'zebra', 'bear', 'panda', 'horse', 'deer', 'wolf',
                    'fox', 'raccoon', 'rabbit', 'squirrel', 'bat', 'seal', 'whale', 'dolphin', 'eagle', 'hawk', 'owl', 'parrot', 'penguin',
                    'shark', 'octopus', 'jellyfish', 'crab', 'lobster', 'starfish', 'sea urchin', 'moose', 'buffalo', 'hamster', 'beetle',
                    'antelope', 'monkey', 'lemur'],
        'colors': ['red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink', 'brown', 'black', 'white', 'gray', 'cyan', 'magenta',
                   'indigo', 'violet', 'turquoise', 'beige', 'lime', 'maroon', 'navy', 'teal', 'olive', 'gold', 'silver', 'bronze', 'cream',
                   'lavender', 'salmon', 'peach', 'rose', 'plum', 'emerald', 'sapphire', 'ruby', 'amber', 'ivory', 'charcoal', 'crimson'],
                'seasons': ['spring', 'summer', 'autumn', 'winter', 'rainy', 'dry', 'monsoon', 'harvest', 'wet', 'warm', 'cold', 'hot', 'cool',
                    'breezy', 'stormy', 'foggy', 'sunny', 'cloudy', 'windy', 'chilly', 'mild', 'temperate', 'arctic', 'tropical', 'humid',
                    'damp', 'blustery', 'crisp', 'frosty', 'overcast', 'drizzly', 'hazy', 'gloomy', 'muggy', 'pleasant', 'stormy', 'snowy'],
        'cities': ['new york', 'los angeles', 'chicago', 'houston', 'phoenix', 'philadelphia', 'san antonio', 'san diego', 'dallas', 'san jose',
                   'austin', 'jacksonville', 'san francisco', 'columbus', 'indianapolis', 'fort worth', 'charlotte', 'detroit', 'el paso', 'memphis',
                   'boston', 'seattle', 'denver', 'nashville', ' baltimore', 'oklahoma city', 'las vegas', 'milwaukee', 'albuquerque', 'tucson',
                   'fresno', 'sacramento', 'kansas city', 'mesa', 'atlanta', 'colorado springs', 'omaha', 'raleigh', 'miami', 'cleveland'],
        'plants': ['rose', 'tulip', 'daffodil', 'sunflower', 'lily', 'orchid', 'daisy', 'lily', 'iris', 'lavender', 'chrysanthemum', 'peony',
                   'jasmine', 'violet', 'pansy', 'hibiscus', 'cactus', 'fern', 'bamboo', 'dandelion', 'marigold', 'dahlia', 'geranium', 'petunia',
                   'begonia', 'zinnia', 'lily of the valley', 'calla lily', 'hydrangea', 'poppy', 'hollyhock', 'cosmos', 'snapdragon', 'sunflower',
                   'lupine', 'asters', 'heather', 'hosta', 'hibiscus', 'gladiolus'],
        'professions': ['doctor', 'nurse', 'teacher', 'engineer', 'lawyer', 'architect', 'accountant', 'scientist', 'artist', 'chef',
                        'mechanic', 'plumber', 'electrician', 'carpenter', 'nurse', 'pharmacist', 'journalist', 'graphic designer', 'web developer',
                        'musician', 'actor', 'pilot', 'firefighter', 'police officer', 'soldier', 'researcher', 'dentist', 'veterinarian',
                        'hairdresser', 'librarian', 'photographer', 'counselor', 'social worker'],
        'games': ['chess', 'checkers', 'monopoly', 'scrabble', 'risk', 'clue', 'battleship', 'pictionary', 'cards', 'dominoes',
                  'go', 'backgammon', 'jenga', 'trivial pursuit', 'uno', 'mahjong', 'rummikub', 'darts', 'ping pong', 'pool',
                  'poker', 'bridge', 'solitaire', 'cranium', 'taboo', 'scattergories', 'bingo', 'operation', 'twister', 'connect four', 'stratego'],
        'technologies': ['computer', 'smartphone', 'tablet', 'internet', 'robot', 'drone', 'software', 'hardware', 'network', 'server',
                         'database', 'algorithm', 'artificial intelligence', 'machine learning', 'blockchain', 'cloud computing', 'cybersecurity',
                         'virtual reality', 'augmented reality', '5G', 'Wi-Fi', 'Bluetooth', 'GPS', 'IoT', 'big data', 'quantum computing',
                         '3D printing', 'nanotechnology', 'bioengineering', 'data science', 'wearables', 'smartwatch', 'smart home'],
        'historical_figures': ['napoleon', 'cleopatra', 'einstein', 'churchill', 'lincoln', 'gandhi', 'martha', 'winston', 'mlk', 'roosevelt',
                               'socrates', 'plato', 'aristotle', 'alexander', 'julius caesar', 'charlemagne', 'shakespeare', 'jesus', 'muhammad', 'homer',
                               'da vinci', 'michaelangelo', 'marx', 'lenin', 'stalin', 'fdr', 'jfk', 'reagan', 'thatcher', 'churchill'],
        'landmarks': ['eiffel tower', 'statue of liberty', 'great wall of china', 'taj mahal', 'pyramids of giza', 'colosseum', 'big ben', 'sydney opera house',
                      'christ the redeemer', 'stonehenge', 'machu picchu', 'acropolis', 'leaning tower of pisa', 'niagara falls', 'golden gate bridge',
                      'petra', 'angkor wat', 'golden temple', 'sagrada familia', 'great barrier reef', 'grand canyon', 'statue of unity', 'seattle space needle',
                      'buckingham palace', 'st basil’s cathedral', 'forbidden city', 'mount rushmore', 'chichen itza', 'the parthenon', 'the alhambra', 'shwedagon pagoda'],
        'technology': ['computer', 'smartphone', 'tablet', 'internet', 'robot', 'drone', 'software', 'hardware', 'network', 'server',
                       'database', 'algorithm', 'artificial intelligence', 'machine learning', 'blockchain', 'cloud computing', 'cybersecurity',
                       'virtual reality', 'augmented reality', '5G', 'Wi-Fi', 'Bluetooth', 'GPS', 'IoT', 'big data', 'quantum computing',
                       '3D printing', 'nanotechnology', 'bioengineering', 'data science', 'wearables', 'smartwatch', 'smart home'],
        'weather': ['sunny', 'cloudy', 'rainy', 'stormy', 'windy', 'foggy', 'snowy', 'icy', 'humid', 'dry', 'cold', 'hot', 'mild', 'breezy',
                    'blustery', 'drizzly', 'overcast', 'gloomy', 'clear', 'pleasant', 'warm', 'cool', 'tropical', 'temperate', 'arctic', 'rainbow',
                    'hail', 'thunderstorm', 'hailstorm', 'dust storm', 'sleet', 'showers', 'frost', 'freezing rain', 'squall', 'muggy'],
        'mythology': ['zeus', 'hera', 'poseidon', 'hades', 'athena', 'apollo', 'artemis', 'hermes', 'ares', 'aphrodite',
                      'demeter', 'dionysus', 'persephone', 'hephaestus', 'hestia', 'chiron', 'medusa', 'centaur', 'minotaur', 'cyclops',
                      'hydra', 'cerberus', 'sirens', 'satyr', 'nymph', 'tantalus', 'icarus', 'daemon', 'nymph', 'hydra', 'furies'],
        'mammals': ['lion', 'tiger', 'elephant', 'bear', 'dolphin', 'whale', 'hippopotamus', 'giraffe', 'zebra', 'kangaroo', 'panda',
                    'koala', 'otter', 'wolf', 'fox', 'raccoon', 'bat', 'camel', 'moose', 'seal', 'beaver', 'rabbit', 'squirrel', 'hedgehog',
                    'coyote', 'panther', 'cheetah', 'sloth', 'wolverine', 'aardvark', 'antelope', 'baboon', 'bison', 'armadillo'],
        'reptiles': ['snake', 'lizard', 'gecko', 'chameleon', 'iguana', 'komodo dragon', 'turtle', 'crocodile', 'alligator', 'gila monster',
                     'horned toad', 'skink', 'anole', 'boa', 'python', 'rattlesnake', 'cobra', 'vipers', 'python', 'monitor lizard',
                     'tortoise', 'basilisk', 'glass lizard', 'legless lizard', 'water dragon', 'flying dragon', 'caiman', 'skink', 'terrapin'],
          'famous_people': ['einstein', 'shakespeare', 'mona lisa', 'gandhi', 'nelson mandela', 'marilyn monroe', 'steve jobs', 'oprah', 'lincoln', 'churchill',
                          'turing', 'da vinci', 'eiffel', 'napoleon', 'tchaikovsky', 'heisenberg', 'mozart', 'dali', 'mlk', 'george washington',
                          'frida kahlo', 'van gogh', 'tesla', 'curie', 'alexander graham bell', 'beyonce', 'madonna', 'john lennon', 'charlie chaplin', 'diana'],
        'furniture': ['sofa', 'chair', 'table', 'bed', 'desk', 'cabinet', 'shelf', 'stool', 'bench', 'dresser', 'wardrobe', 'bookshelf', 'armchair',
                      'ottoman', 'nightstand', 'side table', 'chest', 'hutch', 'bunk bed', 'futon', 'recliner', 'buffet', 'vanity', 'console', 'rocking chair',
                      'daybed', 'beanbag', 'bar stool', 'easel', 'console table', 'bean bag', 'folding chair', 'barbecue'],
        'oceans': ['atlantic', 'pacific', 'indian', 'arctic', 'southern', 'caribbean', 'mediterranean', 'red sea', 'baltic', 'adriatic', 'arabian',
                   'south china sea', 'timor', 'sea of japan', 'black sea', 'north sea', 'philippine sea', 'andaman sea', 'bay of bengal', 'mozambique',
                   'coral sea', 'tasman sea', 'straits of malacca', 'jordan', 'lagoons', 'great australian bight', 'palk strait', 'seas of okhotsk'],
        'planets': ['mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto', 'haumea', 'makemake', 'eris', 'ceres', 'juno',
                    'pallas', 'vesta', 'chiron', 'sedna', '2007 OR10', '2002 MS4', '2004 DW', '2004 KV18', '2002 AW197', '2003 EL61', '2005 RN43', '2010 TK7'],
        'tools': ['hammer', 'screwdriver', 'wrench', 'pliers', 'drill', 'saw', 'level', 'tape measure', 'clamps', 'chisel', 'sander', 'router', 'file',
                  'plier', 'axe', 'mallet', 'crowbar', 'shovel', 'spade', 'trowel', 'ladder', 'welding torch', 'heat gun', 'paintbrush', 'roller', 'scraper',
                  'utility knife', 'glue gun', 'caliper', 'stud finder', 'screw gun', 'nutdriver'],
        'inventions': ['wheel', 'printing press', 'light bulb', 'telephone', 'internet', 'airplane', 'automobile', 'television', 'radio', 'microwave',
                       'camera', 'computer', 'refrigerator', 'electricity', 'steam engine', 'typewriter', 'photograph', 'nuclear reactor', 'solar panel', 'GPS',
                       'laser', 'robot', 'satellite', 'dynamite', 'vacuum cleaner', 'dishwasher', 'barbed wire', 'fountain pen', 'scissors', 'toothbrush'],
        'emotions': ['joy', 'sadness', 'anger', 'fear', 'surprise', 'disgust', 'trust', 'anticipation', 'love', 'happiness', 'frustration', 'excitement',
                     'contentment', 'guilt', 'shame', 'envy', 'pride', 'relief', 'hope', 'boredom', 'loneliness', 'despair', 'embarrassment', 'gloom', 'optimism',
                     'resentment', 'curiosity', 'satisfaction', 'jealousy', 'serenity', 'anxiety'],
        'mythical_creatures': ['dragon', 'unicorn', 'griffin', 'phoenix', 'chimera', 'centaur', 'minotaur', 'gorgon', 'sphinx', 'mermaid', 'kraken',
                              'hydra', 'cyclops', 'fairy', 'gnome', 'leprechaun', 'sprite', 'yeti', 'loch ness monster', 'kitsune', 'basilisk', 'selkie',
                              'wraith', 'vampire', 'werewolf', 'djinn', 'manticore', 'wendigo', 'kitsune', 'jinn'],
          }

    if category in words:
        return random.choice(words[category])
    else:
        raise ValueError(f"Category '{category}' not found. Available categories are: {', '.join(words.keys())}.")

